In [1]:
import holodeck
import numpy as np
import cv2

In [6]:
env = holodeck.make('UrbanCity-MaxDistance')
# The UAV takes 3 torques and a thrust as a command.
command = np.array([0, 0, 0, 100])

env.reset()
for _ in range(500):
   state, reward, terminal, info = env.step(command)
   print(state['LocationSensor'])

[-1.1920929e-09 -4.6566128e-12 -3.3483543e-02]
[-1.1920929e-09 -4.6566128e-12 -4.8268929e-02]
[-1.1920929e-09 -4.6566128e-12 -6.0314007e-02]
[-1.1920929e-09 -4.6566128e-12 -6.9675200e-02]
[-1.1920929e-09 -4.6566128e-12 -7.6407783e-02]
[-1.1920929e-09 -4.6566128e-12 -8.0565900e-02]
[-1.1920929e-09 -4.6566128e-12 -8.2202598e-02]
[-1.1920929e-09 -4.6566128e-12 -8.1369802e-02]
[-1.1920929e-09 -4.6566128e-12 -7.8118376e-02]
[-1.1920929e-09 -4.6566128e-12 -7.2498165e-02]
[-1.1920929e-09 -4.6566128e-12 -6.4557962e-02]
[-1.1920929e-09 -4.6566128e-12 -5.4345522e-02]
[-1.1920929e-09 -4.6566128e-12 -4.1907653e-02]
[-1.1920929e-09 -4.6566128e-12 -2.7290192e-02]
[-1.1920929e-09 -4.6566128e-12 -1.0538043e-02]
[-1.1920929e-09 -4.6566128e-12  8.3048251e-03]
[-1.1920929e-09 -4.6566128e-12  2.9195365e-02]
[-1.1920929e-09 -4.6566128e-12  5.2091349e-02]
[-1.1920929e-09 -4.6566128e-12  7.6951504e-02]
[-1.1920929e-09 -4.6566128e-12  1.0373535e-01]
[-1.1920929e-09 -4.6566128e-12  1.3240327e-01]
[-1.1920929e-

In [ ]:
env = holodeck.make("MazeWorld-FinishMazeSphere")
env.act('sphere0', [0])

for _ in range(10):
   state = env.tick()

   pixels = state['RGBCamera']
   cv2.namedWindow("Camera Output")
   cv2.moveWindow("Camera Output", 500, 500)
   cv2.imshow("Camera Output", pixels[:, :, 0:3])
   cv2.waitKey(0)
   cv2.destroyAllWindows()

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to target thread (0x5606d1013e30)

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to target thread (0x5606d1013e30)

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to target thread (0x5606d1013e30)

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to target thread (0x5606d1013e30)

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to target thread (0x5606d1013e30)

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to target thread (0x5606d1013e30)

QObject::moveToThread: Current thread (0x5606d1013e30) is not the object's thread (0x5606d0608250).
Cannot move to tar