In [1]:
import holodeck
import numpy as np
import cv2

In [16]:
env = holodeck.make('UrbanCity-MaxDistance')
# The UAV takes 3 torques and a thrust as a command.


env.reset()
for i in range(500):
   if i == 0:
      command = np.array([-1, -1, 0, 100])
   else:
      command = np.array([0, 0, 0, 100])
   state, reward, terminal, info = env.step(command)
   print(state['LocationSensor'])

[-1.1920929e-09 -4.6566128e-12 -3.3483543e-02]
[-0.00039184  0.00036206 -0.04823885]
[-0.00111187  0.00102736 -0.06022444]
[-0.00179096  0.00165484 -0.06952265]
[-0.00240606  0.0022232  -0.07618935]
[-0.00293512  0.00271204 -0.08027938]
[-0.00335697  0.00310183 -0.08184651]
[-0.00365141  0.00337388 -0.08094356]
[-0.00379906  0.00351032 -0.07762225]
[-0.00378146  0.00349405 -0.07193365]
[-0.00358093  0.00330876 -0.06392761]
[-0.00318062  0.00293888 -0.05365311]
[-0.00256443  0.00236952 -0.0411582 ]
[-0.00171704  0.00158654 -0.02649011]
[-0.00062385  0.00057642 -0.00969513]
[ 0.00072907 -0.00067367  0.00918156]
[ 0.00235491 -0.00217595  0.03009514]
[ 0.00426625 -0.00394203  0.05300215]
[ 0.006475   -0.00598292  0.07785988]
[ 0.00899247 -0.00830906  0.1046261 ]
[ 0.01182938 -0.01093035  0.1332599 ]
[ 0.01499585 -0.01385616  0.16372071]
[ 0.01850145 -0.01709534  0.1959693 ]
[ 0.02235521 -0.02065621  0.22996652]
[ 0.02656566 -0.02454666  0.2656747 ]
[ 0.03114081 -0.02877408  0.30305645]
[ 0