In [2]:
import holodeck
import numpy as np
import cv2

In [9]:
env = holodeck.make('UrbanCity-MaxDistance')
# The UAV takes 3 torques and a thrust as a command.
command = np.array([0, 0, 50, 100])

env.reset()
for _ in range(500):
   state, reward, terminal, info = env.step(command)
   print(state['LocationSensor'])

[-1.1920929e-09 -4.6566128e-12 -3.3483543e-02]
[ 3.5762785e-08 -1.5406606e-05 -4.8268948e-02]
[ 2.2649765e-07 -5.9401773e-05 -6.0314044e-02]
[ 8.2254405e-07 -1.3139319e-04 -6.9675252e-02]
[ 2.2172928e-06 -2.3079557e-04 -7.6407768e-02]
[ 4.9340724e-06 -3.5702685e-04 -8.0565862e-02]
[ 9.6285339e-06 -5.0950423e-04 -8.2202636e-02]
[ 1.7088651e-05 -6.8763684e-04 -8.1369817e-02]
[ 2.8194188e-05 -8.9082215e-04 -7.8118399e-02]
[ 4.3925047e-05 -1.1184376e-03 -7.2498165e-02]
[ 6.5362452e-05 -1.3698342e-03 -6.4557925e-02]
[ 9.3649622e-05 -1.6443273e-03 -5.4345559e-02]
[ 0.00013003 -0.00194119 -0.04190762]
[ 0.00017579 -0.00225965 -0.02729021]
[ 0.00023228 -0.00259887 -0.01053802]
[ 0.00030088 -0.00295795  0.00830484]
[ 0.00038302 -0.00333593  0.02919542]
[ 0.00048014 -0.00373175  0.05209137]
[ 0.00059372 -0.00414429  0.07695162]
[ 0.00072521 -0.00457231  0.10373539]
[ 0.00087609 -0.00501449  0.13240339]
[ 0.00104778 -0.00546941  0.16291656]
[ 0.0012417  -0.00593553  0.19523709]
[ 0.00145921 -0.00